_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
                - 76
            "2":
                - 1
                - 55
                - 76
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "8":
                - 3
                - 5
                - 13
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 32
dropout_rate:
    value: 0.2
fft_n:
    value: 1024
gamma:
    value: 1
hid_layer:
    value: 0
learning_rate:
    value: 0.001
mode_N:
    value: 7
model_dim:
    value: 64
model_name:
    value: SAGE2MLP1
step_size:
    value: 100
time_0:
    value: 2000
time_L:
    value: 2000
train_N:
    value: 10
