_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 55
                - 76
            "2":
                - 1
                - 55
                - 76
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch_size:
    value: 64
dropout_rate:
    value: 0.1
fft_n:
    value: 1024
gamma:
    value: 1
hid_layer:
    value: 1
learning_rate:
    value: 0.0005
mode_N:
    value: 7
model_dim:
    value: 64
model_name:
    value: SAGE_1st
step_size:
    value: 100
time_0:
    value: 2000
time_L:
    value: 2000
train_N:
    value: 64
