shared:
    mode_N: 7 
    time_L: 2000
    time_0_list: [1000]
    time_0: [1000]
    fs: 200

model:
    name: "Benchmark"
    # name: "NoGNN"
    # name: "LSTM"
    dim: 128
    fft_n: 1024
    dropout_rate: 0
    hid_layer: 1
    
data:
    path: "./truss_dataset.mat"
    bs: 64
    
train:
    learning_rate: 0.0003
    epochs: 5000
    step_size: 1000
    gamma: 0.9