shared:
    mode_N: 7
    time_L: 500
    time_0: 2000

model:
    # name: "SAGE"
    # name: "SAGE_CNN1D"
    # name: "SAGE_CNN2D"
    # name: "SAGE2MLP1"
    # name: "SAGE2MLP2"
    # name: "SAGE_LSTM_TopK"
    # name: "SAGE_Set2Set"  # does not work
    # name: "SAGE_MLP_encoder"
    name: "SAGE_1st"
    # name: "SAGE_1st_noise"
    # name: "SAGE_1st_LSTM"
    # name: "SAGE_LSTM_encoder"
    # name: "SAGE_two"
    # name: "2SAGE_1st"
    # name: "GINE"
    # name: "EdgeGAT"
    # name: "CFC"
    # name: "GatedGraphConv"
    # name: "STGNN"
    dim: 64
    fft_n: 1024
    dropout_rate: 0.1
    hid_layer: 0
    
data:
    # path: "C:/Users/14360/Desktop/trapezoid_time_bottom_input_100sample_lowpass.mat" # local, 100 truss dataset
    # path: "/cluster/work/ibk_chatzi/Xudong//trapezoid_time_bottom_input_100sample_lowpass.mat" # ETH Euler, 100 truss dataset
    path: "C:/Users/xudjian/Desktop/truss_500_lowpass.mat" # local, 500 truss dataset
    # path: "/cluster/work/ibk_chatzi/Xudong//truss_500_lowpass.mat" # ETH Euler, 500 truss dataset
    
    bs: 128
    
train:
    learning_rate: 0.0003
    epochs: 50000
    step_size: 10000
    gamma: 1