shared:
    mode_N: 7
    time_L: 2000
    time_0: 2000

model:
    # name: "SAGE"
    # name: "SAGE_CNN1D"
    # name: "SAGE_CNN2D"
    # name: "SAGE2MLP1"
    # name: "SAGE2MLP2"
    # name: "SAGE_LSTM_TopK"
    # name: "SAGE_Set2Set"  # does not work
    # name: "SAGE_1st"
    # name: "SAGE_1st_LSTM"
    name: "SAGE_LSTM_encoder"
    # name: "GINE"
    # name: "EdgeGAT"
    # name: "CFC"
    # name: "GatedGraphConv"
    dim: 64
    fft_n: 1024
    dropout_rate: 0.2
    hid_layer: 0
    
data:
    # path: "C:/Users/14360/Desktop/trapezoid_time_bottom_input_100sample_lowpass.mat" # local
    path: "/cluster/work/ibk_chatzi/Xudong//trapezoid_time_bottom_input_100sample_lowpass.mat" # ETH Euler
    bs: 64
    
train:
    learning_rate: 0.0005
    epochs: 5000
    step_size: 100
    gamma: 1